### ISSUE TITLE
Are you sure it's working

### ISSUE THREAD

**Issue by rabol** [bambamboole/laravel-translation-dumper#3]
Hi

I have plenty of {{__('xxx')}} in my blade files but after installing this package I do not see anything being added to any files

Did I miss anything ?

**Comment by bambamboole** [comment]
Sorry for the late reply. The package does currently only support dotted strings as translations. Maybe I can have a look into this tonight.

**Comment by bambamboole** [comment]
For now we will only support dotted strings. Nevertheless, I would accept a PR for this.
